### ISSUE TITLE
recent changes

### ISSUE THREAD

**Issue by RisingLeaf** [Wyrdean/Pug-Defense#1]
/Users/pi/Documents/GitHub/EndlessSky-PluginArchive/Working/All Plugins/Pug Defense/Normal Human~Pug Defense test pilot.txt
  3078,3: 		accompany
please add a save tag to this npc, due to recent changes

**Comment by Wyrdean** [comment]
Oh?
I'll check it out in a bit, thanks
What change was this in particular?

**Comment by RisingLeaf** [comment]
accompany no longer requires you to keep the npc alive

**Comment by RisingLeaf** [comment]
Can I close this?

**Comment by Wyrdean** [comment]
I did fix it in my version, but as I haven't (unfortunately) gotten around to completing the update, closing the issue is for the best.
